# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'l0lHOWY6dh691O7pXUjJRQatk'
  twitter_api_secret: 'MDtxemDAodEyGJTJwY6D8DQUY1tulowfy9dpzVb119qotSTawu'

development:
  secret_key_base: 78f5968270ddaa310165b8025152a48c962018648b84e7a5688bb917574ee2db0ed5ba6d3e45180fe5115fcc3f528ee70a54fa9f65a68157213639f480b4817b
  <<: *default_twitter

test:
  secret_key_base: edf5624c8f4e5ac82b28fd8dd2a38bd0287eca47adc7c44919e24da43ad7b0fb6231e1ad2b828f3cba11378ab2594eaecdf102bea46519bd5e6a84ad754fd5d7
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
